from __future__ import annotations

import pytest

from text_verification.compatibility.analyzer import TextAnalyzer


# Captured from the supplied legacy analyzer, not generated by the migrated engine.
@pytest.mark.parametrize(
    ("text", "expected"),
    [
        (
            "按步就班，迫不急待。",
            [
                ("cn_typo", "按步就班", "按部就班", 0, 4),
                ("cn_typo", "迫不急待", "迫不及待", 5, 9),
            ],
        ),
        ("This is teh adress.", [("en_spelling", "adress", "address", 12, 18)]),
        ("中文,,句子。", [("mixed_punct", ",", "，", 2, 3)]),
        ("我们我们正在检查。", [("repeat_word_cn", "我们我们", "我们", 0, 4)]),
        ("文档中的帐号与账号应统一。", [("cn_typo", "帐号", "账号", 4, 6)]),
        ("AI和APP都很好。", [("custom_glossary", "AI", "人工智能", 0, 2)]),
        (
            "这是唯一最佳的产品。",
            [
                ("banned_word", "唯一", "（请替换或删除该禁用词）", 2, 4),
                ("ad_extreme_words", "最佳", None, 4, 6),
            ],
        ),
        ("香港和中国香港。", [("sensitive_rules", "香港", "中国香港", 0, 2)]),
        ("联系 person@example.test。", [("pii_email", "person@example.test", "***", 3, 22)]),
    ],
)
@pytest.mark.parametrize("scenario", [
    "general", "academic", "business", "legal", "news", "technical",
])
def test_legacy_reference_findings_keep_suggestions_and_exact_source_spans(
    text: str, expected: list[tuple[str, str, str | None, int, int]], scenario: str,
) -> None:
    issues = TextAnalyzer().analyze(
        text, scenario=scenario, enable_ad_extreme=True,
        custom_glossary=[{"original": "AI", "standard": "人工智能"}],
        banned_words=["唯一"],
    )
    assert [
        (issue.rule_id, issue.original, issue.suggestion, issue.position, issue.end_position)
        for issue in issues
    ] == expected
